version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0 #7.11
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./tmp/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

# volumes:
#   data01:
#     driver: local

networks:
  elastic:
    driver: bridge

# version: '3'
# services:
#   es:
#     image: elasticsearch:6.7.0
#     ports:
#       - "9200:9300"
#     volumes:
#       - ./tmp/es:/usr/share/elasticsearch/data
